apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-js
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-node-js
  template:
    metadata:
      labels:
        app: k8s-node-js
    spec:
      containers:
      - name: k8s-node-js
        image: 'sayalok/simple-node-js'
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
